version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: axel
      POSTGRES_PASSWORD: avalanche
      POSTGRES_DB: avalanche
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
